[29/03/18] 10:46:28 [ERROR] [Application] TypeError: this._model.removeById is not a function
[29/03/18] 10:46:28 [ERROR] [Application]     at Species._callee6$ (/home/ubuntu/workspace/NEA/models/species.js:95:31)
[29/03/18] 10:46:28 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:46:28 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:46:28 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:46:28 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/models/species.js:35:191)
[29/03/18] 10:46:28 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/models/species.js:35:437
[29/03/18] 10:46:28 [ERROR] [Application]     at new Promise (<anonymous>)
[29/03/18] 10:46:28 [ERROR] [Application]     at Species.<anonymous> (/home/ubuntu/workspace/NEA/models/species.js:35:99)
[29/03/18] 10:46:28 [ERROR] [Application]     at Species.removeSpeciesByID (/home/ubuntu/workspace/NEA/models/species.js:94:16)
[29/03/18] 10:46:28 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:309:42)
[29/03/18] 10:46:28 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:46:28 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:46:28 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:46:28 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:46:28 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:46:28 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:46:28 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[29/03/18] 10:46:28 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[29/03/18] 10:46:28 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[29/03/18] 10:46:28 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[29/03/18] 10:51:38 [ERROR] [Application] Error: Can't set headers after they are sent.
[29/03/18] 10:51:38 [ERROR] [Application]     at validateHeader (_http_outgoing.js:494:11)
[29/03/18] 10:51:38 [ERROR] [Application]     at ServerResponse.setHeader (_http_outgoing.js:501:3)
[29/03/18] 10:51:38 [ERROR] [Application]     at Function.sendJSONResponse (/home/ubuntu/workspace/NEA/lib/utils.js:44:18)
[29/03/18] 10:51:38 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:335:31)
[29/03/18] 10:51:38 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:51:38 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:51:38 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:51:38 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:51:38 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:51:38 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:51:38 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[29/03/18] 10:51:38 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[29/03/18] 10:51:38 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[29/03/18] 10:51:38 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[29/03/18] 10:51:38 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[29/03/18] 10:51:38 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[29/03/18] 10:54:27 [ERROR] [Application] Error: Can't set headers after they are sent.
[29/03/18] 10:54:27 [ERROR] [Application]     at validateHeader (_http_outgoing.js:494:11)
[29/03/18] 10:54:27 [ERROR] [Application]     at ServerResponse.setHeader (_http_outgoing.js:501:3)
[29/03/18] 10:54:27 [ERROR] [Application]     at Function.sendJSONResponse (/home/ubuntu/workspace/NEA/lib/utils.js:44:18)
[29/03/18] 10:54:27 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:336:31)
[29/03/18] 10:54:27 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:54:27 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:54:27 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:54:27 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:54:27 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:54:27 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:54:27 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[29/03/18] 10:54:27 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[29/03/18] 10:54:27 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[29/03/18] 10:54:27 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[29/03/18] 10:54:27 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[29/03/18] 10:54:27 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[29/03/18] 10:55:52 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[29/03/18] 10:55:52 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[29/03/18] 10:55:52 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:55:52 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:55:52 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:55:52 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:55:52 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:55:52 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:05 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:05 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:05 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:05 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:05 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:57:05 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:05 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:05 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:05 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:05 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[29/03/18] 10:57:05 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[29/03/18] 10:57:05 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[29/03/18] 10:57:05 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[29/03/18] 10:57:20 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:20 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:20 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:20 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:20 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:57:20 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:20 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:20 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:20 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:20 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:20 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:20 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:20 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:20 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:57:20 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:20 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:20 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:20 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:33 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:33 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:33 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:33 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:33 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:57:33 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:33 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:33 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:33 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:34 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:34 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:34 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:34 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:34 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:57:34 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:34 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:34 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:34 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:36 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:57:36 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:57:36 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:57:36 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:57:36 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:57:36 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:57:36 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:57:36 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[29/03/18] 10:57:36 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:59:19 [ERROR] [Application] TypeError: loggedInUser.indexOf is not a function
[29/03/18] 10:59:19 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:318:74)
[29/03/18] 10:59:19 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[29/03/18] 10:59:19 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[29/03/18] 10:59:19 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[29/03/18] 10:59:19 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[29/03/18] 10:59:19 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[29/03/18] 10:59:19 [ERROR] [Application]     at <anonymous>
[29/03/18] 10:59:19 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[30/03/18] 09:32:11 [ERROR] [Application] TypeError: userDoc.indexOf is not a function
[30/03/18] 09:32:11 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:323:68)
[30/03/18] 09:32:11 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:32:11 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:32:11 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:32:11 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:32:11 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[30/03/18] 09:32:11 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:32:11 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[30/03/18] 09:32:11 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[30/03/18] 09:32:11 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[30/03/18] 09:32:11 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[30/03/18] 09:32:11 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:33:25 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:33:25 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:33:25 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:33:25 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:33:25 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:33:25 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:33:25 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:33:25 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:33:25 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[30/03/18] 09:33:25 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[30/03/18] 09:33:25 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[30/03/18] 09:33:25 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[30/03/18] 09:33:25 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[30/03/18] 09:33:25 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[30/03/18] 09:33:25 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:33:25 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:33:25 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:33:25 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:33:25 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:33:25 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:33:25 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:33:25 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:33:26 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:33:26 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:33:26 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:33:26 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:33:26 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:33:26 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:33:26 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:33:26 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:33:26 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:33:26 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:33:26 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:33:26 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:33:26 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:33:26 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:33:26 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:33:26 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:35:26 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:35:26 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:35:26 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:35:26 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:35:26 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:35:26 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:35:26 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:35:26 [ERROR] [Application]     at <anonymous>
[30/03/18] 09:35:26 [ERROR] [Application] TypeError: Cannot read property 'count' of null
[30/03/18] 09:35:26 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:278:50)
[30/03/18] 09:35:26 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[30/03/18] 09:35:26 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[30/03/18] 09:35:26 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[30/03/18] 09:35:26 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[30/03/18] 09:35:26 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[30/03/18] 09:35:26 [ERROR] [Application]     at <anonymous>
[01/04/18] 07:53:21 [ERROR] [Application] TypeError: Cannot read property 'splice' of undefined
[01/04/18] 07:53:21 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 07:53:21 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 07:53:21 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 07:53:21 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 07:53:21 [ERROR] [Application]     at <anonymous>
[01/04/18] 07:53:21 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[01/04/18] 07:53:21 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/04/18] 07:53:21 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:301:40)
[01/04/18] 07:53:21 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[01/04/18] 07:53:21 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[01/04/18] 07:53:21 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[01/04/18] 07:53:21 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 07:54:54 [ERROR] [Application] TypeError: Cannot read property 'splice' of undefined
[01/04/18] 07:54:54 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:301:40)
[01/04/18] 07:54:54 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 07:54:54 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 07:54:54 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 07:54:54 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 07:54:54 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 07:54:54 [ERROR] [Application]     at <anonymous>
[01/04/18] 07:54:54 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[01/04/18] 07:54:54 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/04/18] 07:54:54 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[01/04/18] 07:54:54 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[01/04/18] 07:54:54 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[01/04/18] 07:57:49 [ERROR] [Routes/Admin] WriteError({"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: wildlife_website_db.taxonomicgroups.$name_1  dup key: { : \"Test Group\" }","op":{"optionalFields":[],"invalidFields":[],"statuses":[],"species":[],"_id":"5ae81dfd90bfcd08e14f8cca","name":"Test Group","__v":0}})
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at /home/ubuntu/workspace/NEA/node_modules/mongodb/lib/bulk/unordered.js:535:15
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at handleCallback (/home/ubuntu/workspace/NEA/node_modules/mongodb/lib/utils.js:128:55)
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at resultHandler (/home/ubuntu/workspace/NEA/node_modules/mongodb/lib/bulk/unordered.js:456:5)
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at /home/ubuntu/workspace/NEA/node_modules/mongodb-core/lib/connection/pool.js:544:18
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[01/04/18] 07:57:49 [ERROR] [Routes/Admin]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[01/04/18] 08:07:14 [ERROR] [Application] TypeError: Cannot read property 'toDateString' of undefined
[01/04/18] 08:07:14 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:340:74)
[01/04/18] 08:07:14 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 08:07:14 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 08:07:14 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 08:07:14 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 08:07:14 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 08:07:14 [ERROR] [Application]     at <anonymous>
[01/04/18] 08:07:14 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/04/18] 08:07:14 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[01/04/18] 08:07:14 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[01/04/18] 08:07:14 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[01/04/18] 08:07:14 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[01/04/18] 08:07:14 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[01/04/18] 08:07:14 [ERROR] [Application] TypeError: Cannot read property 'toDateString' of undefined
[01/04/18] 08:07:14 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:340:74)
[01/04/18] 08:07:14 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 08:07:14 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 08:07:14 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 08:07:14 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 08:07:14 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 08:07:14 [ERROR] [Application]     at <anonymous>
[01/04/18] 08:07:15 [ERROR] [Application] TypeError: Cannot read property 'toDateString' of undefined
[01/04/18] 08:07:15 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:340:74)
[01/04/18] 08:07:15 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 08:07:15 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 08:07:15 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 08:07:15 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 08:07:15 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 08:07:15 [ERROR] [Application]     at <anonymous>
[01/04/18] 08:07:16 [ERROR] [Application] TypeError: Cannot read property 'splice' of undefined
[01/04/18] 08:07:16 [ERROR] [Application]     at AdminRouter._callee10$ (/home/ubuntu/workspace/NEA/routes/admin.js:301:40)
[01/04/18] 08:07:16 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 08:07:16 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 08:07:16 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/admin.js:51:191)
[01/04/18] 08:07:16 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/04/18] 08:07:16 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/admin.js:51:361
[01/04/18] 08:07:16 [ERROR] [Application]     at <anonymous>
[01/04/18] 08:07:16 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[01/04/18] 10:08:48 [ERROR] [Application]     at DataUpload._callee7$ (/home/ubuntu/workspace/NEA/models/data-upload.js:125:31)
[01/04/18] 10:08:48 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/04/18] 10:08:48 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/04/18] 10:08:48 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/models/data-upload.js:23:191)
[01/04/18] 10:08:48 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/models/data-upload.js:23:361
[01/04/18] 10:08:48 [ERROR] [Application]     at <anonymous>
[01/04/18] 10:08:48 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[01/04/18] 10:08:48 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/04/18] 10:08:48 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[01/04/18] 10:08:48 [ERROR] [Application] TypeError: Cannot read property 'date' of undefined
[01/04/18] 10:08:48 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[01/04/18] 10:08:48 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[01/04/18] 10:08:48 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload] ValidationError: location: Path `location` is required.
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at /home/ubuntu/workspace/NEA/node_modules/mongoose/lib/document.js:1630:17
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at /home/ubuntu/workspace/NEA/node_modules/mongoose/lib/schematype.js:808:9
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at new ValidationError (/home/ubuntu/workspace/NEA/node_modules/mongoose/lib/error/validation.js:27:11)
[23/06/18] 16:27:52 [ERROR] [Routes/DataUpload]     at model.Document.invalidate (/home/ubuntu/workspace/NEA/node_modules/mongoose/lib/document.js:1758:32)
[01/07/18] 21:57:22 [ERROR] [Application] TypeError: Cannot read property 'length' of undefined
[01/07/18] 21:57:22 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/lib/validator.js:300:55
[01/07/18] 21:57:22 [ERROR] [Application]     at DataUploadRouter._validateNewLocationData (/home/ubuntu/workspace/NEA/routes/data-upload.js:275:38)
[01/07/18] 21:57:22 [ERROR] [Application]     at Array.forEach (<anonymous>)
[01/07/18] 21:57:22 [ERROR] [Application]     at DataUploadRouter._callee2$ (/home/ubuntu/workspace/NEA/routes/data-upload.js:51:32)
[01/07/18] 21:57:22 [ERROR] [Application]     at tryCatch (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:65:40)
[01/07/18] 21:57:22 [ERROR] [Application]     at Generator.invoke [as _invoke] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:303:22)
[01/07/18] 21:57:22 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/NEA/node_modules/regenerator-runtime/runtime.js:117:21)
[01/07/18] 21:57:22 [ERROR] [Application]     at step (/home/ubuntu/workspace/NEA/routes/data-upload.js:55:191)
[01/07/18] 21:57:22 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/data-upload.js:55:437
[01/07/18] 21:57:22 [ERROR] [Application]     at Function.validateLengths (/home/ubuntu/workspace/NEA/lib/validator.js:298:20)
[01/07/18] 21:57:22 [ERROR] [Application]     at new Promise (<anonymous>)
[01/07/18] 21:57:22 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/data-upload.js:55:99
[01/07/18] 21:57:22 [ERROR] [Application]     at /home/ubuntu/workspace/NEA/routes/data-upload.js:47:9
[01/07/18] 21:57:22 [ERROR] [Application]     at Layer.handle [as handle_request] (/home/ubuntu/workspace/NEA/node_modules/express/lib/router/layer.js:95:5)
[01/07/18] 21:57:22 [ERROR] [Application]     at next (/home/ubuntu/workspace/NEA/node_modules/express/lib/router/route.js:137:13)
[01/07/18] 21:57:22 [ERROR] [Application]     at Route.dispatch (/home/ubuntu/workspace/NEA/node_modules/express/lib/router/route.js:112:3)
[01/07/18] 21:57:22 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[01/07/18] 21:57:22 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[01/07/18] 21:57:22 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[01/07/18] 21:57:22 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[01/07/18] 21:57:22 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[01/07/18] 21:57:22 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[01/07/18] 22:03:09 [ERROR] [Models/Location] Failed to create a new location: insertDocument :: caused by :: 11000 E11000 duplicate key error index: wildlife_website_db.locations.$locationName_1  dup key: { : "Test Location" }
[01/07/18] 22:03:21 [ERROR] [Models/Location] Failed to create a new location: insertDocument :: caused by :: 11000 E11000 duplicate key error index: wildlife_website_db.locations.$locationName_1  dup key: { : "Test Location" }
[12/07/18] 02:28:01 [ERROR] [Models/Location] Failed to create a new location: insertDocument :: caused by :: 11000 E11000 duplicate key error index: wildlife_website_db.locations.$locationName_1  dup key: { : "Test Location" }
[12/07/18] 02:48:34 [ERROR] [Models/Location] Failed to create a new location: insertDocument :: caused by :: 11000 E11000 duplicate key error index: wildlife_website_db.locations.$locationName_1  dup key: { : "Test Location" }
[10/08/18] 08:38:53 [ERROR] [Application] TypeError: Cannot read property 'length' of undefined
[10/08/18] 08:38:53 [ERROR] [Application]     at C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/lib/validator.js:300:55
[10/08/18] 08:38:53 [ERROR] [Application]     at DataUploadRouter._validateNewGroupData (C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/routes/data-upload.js:303:38)
[10/08/18] 08:38:53 [ERROR] [Application]     at Function.validateLengths (C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/lib/validator.js:298:20)
[10/08/18] 08:38:53 [ERROR] [Application]     at DataUploadRouter._callee3$ (C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/routes/data-upload.js:75:32)
[10/08/18] 08:38:53 [ERROR] [Application]     at tryCatch (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:65:40)
[10/08/18] 08:38:53 [ERROR] [Application]     at Generator.invoke [as _invoke] (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:303:22)
[10/08/18] 08:38:53 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:117:21)
[10/08/18] 08:38:53 [ERROR] [Application]     at step (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\routes\data-upload.js:55:191)
[10/08/18] 08:38:53 [ERROR] [Application]     at C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\routes\data-upload.js:55:437
[10/08/18] 08:38:53 [ERROR] [Application]     at new Promise (<anonymous>)
[10/08/18] 08:38:53 [ERROR] [Application]     at C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\routes\data-upload.js:55:99
[10/08/18] 08:38:53 [ERROR] [Application]     at C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/routes/data-upload.js:71:9
[10/08/18] 08:38:53 [ERROR] [Application]     at Layer.handle [as handle_request] (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\express\lib\router\layer.js:95:5)
[10/08/18] 08:38:53 [ERROR] [Application]     at next (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\express\lib\router\route.js:137:13)
[10/08/18] 08:38:53 [ERROR] [Application]     at Array.forEach (<anonymous>)
[10/08/18] 08:38:53 [ERROR] [Application]     at Route.dispatch (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\express\lib\router\route.js:112:3)
[10/08/18] 08:38:53 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/08/18] 08:38:53 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[10/08/18] 08:38:53 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[10/08/18] 08:38:53 [ERROR] [Application]     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
[10/08/18] 08:38:53 [ERROR] [Application]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[10/08/18] 08:38:53 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[10/08/18] 08:41:17 [ERROR] [Application] ReferenceError: log is not defined
[10/08/18] 08:41:17 [ERROR] [Application]     at TaxonomicGroup._callee4$ (C:/Users/Matthew Lester/Desktop/Coding/VSCode Workspace/ARochaWildlifeSite/models/taxonomic-group.js:66:17)
[10/08/18] 08:41:17 [ERROR] [Application]     at tryCatch (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:65:40)
[10/08/18] 08:41:17 [ERROR] [Application]     at Generator.invoke [as _invoke] (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:303:22)
[10/08/18] 08:41:17 [ERROR] [Application]     at Generator.prototype.(anonymous function) [as next] (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\node_modules\regenerator-runtime\runtime.js:117:21)
[10/08/18] 08:41:17 [ERROR] [Application]     at step (C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\models\taxonomic-group.js:27:191)
[10/08/18] 08:41:17 [ERROR] [Application]     at C:\Users\Matthew Lester\Desktop\Coding\VSCode Workspace\ARochaWildlifeSite\models\taxonomic-group.js:27:361
[10/08/18] 08:41:17 [ERROR] [Application]     at <anonymous>
[10/08/18] 08:41:17 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[10/08/18] 08:41:17 [ERROR] [Application] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/08/18] 08:41:17 [ERROR] [Application]     at emitWarning (internal/process/promises.js:78:15)
[10/08/18] 08:41:17 [ERROR] [Application]     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
[10/08/18] 08:41:17 [ERROR] [Application]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
